### ISSUE TITLE
mail import doesn't work even with imap module installed

### ISSUE THREAD

**Issue by RCEurope1** [creativecommons/europe#11]
when I run the mailcheck script manually, I get:

"imap_open failed: Can't open mailbox {pop3.web.de:995/service=pop3/ssl/tls/novalidate-cert}: invalid remote specification
Mail Connection Time Out
Common Reasons: Server Down, Network Issue, Port/Protocol MisMatch 
The Server said:"

(the server saying nothing). Is that on our side or on theirs? can you tell?

**Comment by mvhaen** [comment]
John,

I was sick last week. I'll have a look as soon as I can, but this looks like a configuration mismatch. 

Groeten,
Michael

**Comment by mvhaen** [comment]
I disabled Use Transport Layer Security (TLS). The errors don't show up anymore, can you test again.

**Comment by RCEurope1** [comment]
will do, if it is that easy, I'll apologise :)

**Comment by mvhaen** [comment]
Already tweaked some of the settings since it was forwarding rejected e-mails to admins. And their were a lot of rejected e-mails.

Groeten,
Michael Voorhaen


On 5 March 2016 at 16:56:59, JohnW (notifications@github.com) wrote:

will do, if it is that easy, I'll apologise :)

**Comment by RCEurope1** [comment]
seems to work now, thx lots!

I'm still tinkering around with the settings but getting there ...
