### ISSUE TITLE
twitter import doesn't work for unknown reason

### ISSUE THREAD

**Issue by RCEurope1** [creativecommons/europe#12]
I did a test tweet under my pseudonym (containing the key hashtag #cceurope) here:
https://twitter.com/alice_klarr/status/704178178139394048

@commonseurope follows me but doesn't import it. Is this maybe a cron problem? Can it be tested by running the import manually (like with Postie)?

**Comment by mvhaen** [comment]
John,

The plugin only matches hashtags at the end (not inside the tweet). 

Regards,
Michael

**Comment by RCEurope1** [comment]
oh, stupid me :)  I'll retry, thx for the quick reply.

**Comment by RCEurope1** [comment]
tried again, still not importing. Any idea?

**Comment by RCEurope1** [comment]
ah, now it works
