### ISSUE TITLE
The affiliate wiki data isn't pulled

### ISSUE THREAD

**Issue by mattl** [creativecommons/europe#2]
As noted by Michael in https://creativecommons.freshdesk.com/helpdesk/tickets/15646 -- we'll need php5-curl installed on the server.

@robmyers I thought we were installing this by default with Salt? Let's update the stack to include it.

**Comment by robmyers** [comment]
Adding.

**Comment by mattl** [comment]
php-gd (or is it php5-gd) too, would be good.

**Comment by robmyers** [comment]
Both are in lamp-stack in salt. europe.cc wasn't adding lamp-stack. It is now.

php5-curl is now installed on the server.

**Comment by mattl** [comment]
@RCEurope1 The required components are installed, can you test and see if things are working as expected now?

**Comment by RCEurope1** [comment]
yes, works now. thx
