### ISSUE TITLE
To edit the footer, Michael needs to modify the source code. 

### ISSUE THREAD

**Issue by mattl** [creativecommons/europe#3]
Michael has admin access, and can possibly edit through the web. We'd like to move things over to GitHub once they're stable.

**Comment by robmyers** [comment]
I've just checked, and yes the theme can be edited through WordPress Admin's Themes/Editor page.

Git is the long term solution though.

**Comment by RCEurope1** [comment]
ok, waiting for Michael to respond (he needs to be added to this repo first, right?) ...

**Comment by mvhaen** [comment]
This is ok for me, but I would prefer making the changes on git just to keep track of everything.

I will use my own git repo for now, test on my staging install and copy/paste the changes into the admin panel.

That said. For the changes I need to make to the footer, I will need to fix some input here. I put 'copyright comes here' for the moment, but you haven't gotten back to me what I should put there. If anything?

**Comment by mvhaen** [comment]
I will pick up the 'More' and 'Tags changes' during the weekend, early next week.

**Comment by RCEurope1** [comment]
yes, I haven't sent that yet, will do a.s.a.p.
