### ISSUE TITLE
We want a slight edit of the "More" feature and the Tags.

### ISSUE THREAD

**Issue by mattl** [creativecommons/europe#4]
For that Michael needs access to the GitHub repo to commit the changes.

See #3

**Comment by mvhaen** [comment]
John, remind me what you wanted to replace the 'more' on the teams page with? 'about'?

**Comment by RCEurope1** [comment]
'details' instead of 'more'. Can you also make Gwen & me admins again?

**Comment by mvhaen** [comment]
done.
