### ISSUE TITLE
Postie Plugin is missing

### ISSUE THREAD

**Issue by RCEurope1** [creativecommons/europe#7]
that might have to do with updates, no idea. Please reinstate as shown in the documentation at http://cce.rooster.rooster-solutions.prvw.eu/documentation/

**Comment by mvhaen** [comment]
Not really sure if it has been restored, but as far as I can see the plugin is installed correctly.

**Comment by mvhaen** [comment]
See https://europe.creativecommons.org/wp-admin/plugins.ph: Postie is installed.

**Comment by RCEurope1** [comment]
same here, I don't see "Postie" in the menu anymore.

**Comment by mvhaen** [comment]
This is the same as #8.
