### ISSUE TITLE
Import Tweets as Posts is missing

### ISSUE THREAD

**Issue by RCEurope1** [creativecommons/europe#8]
might also have to do with updates. Please reinstate as shown in documentation at http://cce.rooster.rooster-solutions.prvw.eu/documentation/

**Comment by mvhaen** [comment]
Not really sure if it has been restored, but as far as I can see the plugin is installed correctly.

**Comment by mvhaen** [comment]
See https://europe.creativecommons.org/wp-admin/plugins.ph:  Import Tweets as Posts is installed.

**Comment by RCEurope1** [comment]
when I log in, I don't see the "Settings" part of the menu anymore (was visible last time). Any idea why? Is it a rights/roles issue?

**Comment by mvhaen** [comment]
Yep, you are an Editor and not an Administrator on the site. Only Administrators see the settings part..

**Comment by RCEurope1** [comment]
alright, wasn't aware that I was downgraded. Can someone correct that for Gwen and me?

**Comment by mvhaen** [comment]
John, you and Gwen are are admins again. Not sure why this was changed. Maybe best to follow with @mattl.

**Comment by RCEurope1** [comment]
great, all working again. The tweet import also functional (just tried)
